public class Funcionario {
    Public String nome;
    Public String cpf;
    public Integer matricula;
    
    public funcionario(){}
    public funcionario (String nome, String cpf, Integer matricula){
        this.nome = nome;
        this.cpf = cpf;
        this.matricula = matricula;
    }
}

   // public void funcionarioEmpresa(){}
    /*public void funcionarioEmpresa(){
        System.debug('Nome do funcionario: ' + nome);
        System.debug('cpf do funcionario: ' + cpf);
        System.debug('Matricula do funcionario: ' + matricula);
}*/